from graphics import *

def main():
    window = GraphWin('CS110', 800, 800)
    center = Point(600,200)
    center.draw(window)
    circle = Circle(center, 150)
    circle.setFill('blue')
    circle.draw(window)
    center2 = Point(200,600)
    center2.draw(window)
    circle2 = Circle(center2, 150)
    circle2.setFill('pink')
    circle2.draw(window)
    line = Line(center, center2)
    line.setFill('yellow')
    line.draw(window)
    p1 = Point(400, 400)
    message = Text(p1, "Keep me company on the Moon")
    message.setFill('green')
    message.setSize(35)
    message.draw(window)
main()
input()